### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by angeluslove** [HerikLyma/CPPWebFramework#13]
Love your code style, reading is very comfortable, combined with the Qt development is having a good time, but the network library performance Qt is a bit low, consider under Linux using epoll high load optimization?

**Comment by HerikLyma** [comment]
Hello my friend.

Thanks for your commentary. About using epoll or other libraries, the CWF has a policy of using only C++ and Qt in its development to ensure compatibility between all platforms: Windows, Linux, Mac, Android, iPhone, etc... In addition, the idea is that CWF is also easy to install, avoiding doing what many frameworks do that is having dependence on thousands of other libraries and even other frameworks.


Thank you
Herik Lima

**Comment by angeluslove** [comment]
Thank you for your answer!

Agree with your point of view, and keep it simple is the best idea, there are some projects can make up for the epoll problems based on Qt, but I don't know whether useful, consider integration into the frame!
https://github.com/search?q=qt+epoll
