### ISSUE TITLE
FillObjectBMI example does not show correct results

### ISSUE THREAD

**Issue by paul-reilly** [HerikLyma/CPPWebFramework#19]
When running the FillObjectBMI example, the results page does not show the correct results. It looks like the fields are not being received by UserModel.

**Comment by HerikLyma** [comment]
Hello my friend.

How are you?

We made a small correction in the CWF where the parameters were decoded by default, see if that solves your problem, if it does not solve, please open another issue. Please test the new version.

Note: Thank you very much for your comments.

Best regards.
Herik Lima

**Comment by paul-reilly** [comment]
Thanks very much for the quick fix, that's it working now!
