### ISSUE TITLE
log file, set max size?

### ISSUE THREAD

**Issue by tirolel** [HerikLyma/CPPWebFramework#2]
I just find out that the log file can grow and be a really huge file.  
is there any configuration I can limit the file size?

**Comment by HerikLyma** [comment]
Hi Tirolel,

In this version it is not possible to limit the size of the log file.
We will check this for future versions.


Thank you.

**Comment by tirolel** [comment]
Okay. I see. 
For now I have implemented a variable in the ini file with log max size. and in "cppwebapplication.cpp" after line 66, I added: 
` if(file.size() > configuration.logMaxSize)
        {
           file.resize(0);
        };`

so I clear the log once it reaches to the maximum size that given.

**Comment by HerikLyma** [comment]
Thank you very much Tirolel.

We will implement this feature.
