### ISSUE TITLE
Qt on Win10 can't use C:\ as INCLUDEPATH

### ISSUE THREAD

**Issue by paul-reilly** [HerikLyma/CPPWebFramework#20]
I had to move the C:/cwf directory to C:/cwf/cwf and change the INCLUDEPATH entry for win32 in the pro files to C:/cwf.

I don't know if anybody else can replicate this, but it took a while to find out what was happening so I hope it's a helpful report.

**Comment by HerikLyma** [comment]
Hello my friend.

I use it on Windows 10 without any problem and we also compile it for each commit automaticly on App Veyor for Windows.


Thank you.

**Comment by paul-reilly** [comment]
Hmmm.... interesting, thanks. I'm using MinGW 32 bit - are you using MSVC?
