### ISSUE TITLE
END_OF_MENSAGE,  END_OF_MENSAGE_WITH_ZERO spelling mistakes?

### ISSUE THREAD

**Issue by shujaatak** [HerikLyma/CPPWebFramework#22]
It think END_OF_MENSAGE should be HTTP::END_OF_MESSAGE and END_OF_MENSAGE_WITH_ZERO should be END_OF_MESSAGE_WITH_ZERO?

https://github.com/HerikLyma/CPPWebFramework/blob/d1cede7c23126e127bbce70e5a1914852ca263e3/CPPWebFramework/cwf/constants.h#L128

https://github.com/HerikLyma/CPPWebFramework/blob/d1cede7c23126e127bbce70e5a1914852ca263e3/CPPWebFramework/cwf/constants.h#L129

**Comment by HerikLyma** [comment]
Hello my friend.

You are right, I already modified that.

Many thanks for reporting this.
Herik Lima
