### ISSUE TITLE
How can I achieve html sanitization using CPPWebFramework?

### ISSUE THREAD

**Issue by shujaatak** [HerikLyma/CPPWebFramework#23]
As I have searched the html sanitization feature in CPPWebFramework but I did not find so I wonder how can I achieve this? Can you please give me some hints or point me to some library or tutorials?

**Comment by HerikLyma** [comment]
Hello my friend.

Well, against SQL injection, for example, you can use QSqlQuery::prepare and QSqlQuery::bindValue to avoid SQL injection.


Thank you very much.
Herik Lima
