### ISSUE TITLE
cant compile library in windows 10

### ISSUE THREAD

**Issue by Cintrust** [HerikLyma/CPPWebFramework#27]
i get the following error when compiling on windows with nmake
` cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:__cplusplus -std=c++11 -MD -O3 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DNDEBUG -DCPPWEBFRAMEWORK_LIBRARY -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -D_WINDLL -I. -IC:\Qt\5.13.2\msvc2015_64\include -IC:\Qt\5.13.2\msvc2015_64\include\QtNetwork -IC:\Qt\5.13.2\msvc2015_64\include\QtXml -IC:\Qt\5.13.2\msvc2015_64\include\QtSql -IC:\Qt\5.13.2\msvc2015_64\include\QtCore -Irelease -IC:\Qt\5.13.2\msvc2015_64\mkspecs\win32-msvc -Forelease\ @C:\Users\JUNIOR~1\AppData\Local\Temp\nm4509.tmp
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
cl : Command line warning D9002 : ignoring unknown option '-O3'
configuration.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cppwebapplication.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cppwebserver.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cstlcompiler.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cstlcompilerattributes.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cstlcompilerfor.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cstlcompilerif.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cstlcompilerimport.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
filemanager.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
filterchain.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
httpparser.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
httpreadrequest.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
metaclassparser.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
properties.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
qlistobject.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
requestdispatcher.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
urlencoder.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
sqlquery.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
response.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
request.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
Generating Code...
Compiling...
controller.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
session.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
cppwebcontroller.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
sslloader.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
filter.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
model.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
modelbasicoperation.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
sqlquerymanager.cpp
C:\Qt\5.13.2\msvc2015_64\include\QtCore/qglobal.h(45): fatal error C1083: Cannot open include file: 'type_traits': No such file or directory
Generating Code...
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.EXE"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\nmake.exe"' : return code '0x2'
Stop.`

**Comment by HerikLyma** [comment]
Hello, @Cintrust .

We are going to update de CMake files. For now, you can use the Qt Creator and QMake to compile the projects.


Thank you

**Comment by Cintrust** [comment]
Finally compiled and using the library.
Great work. 

But adding a cmake file also for the examples will also go a long way
