### ISSUE TITLE
can not complie on windows beacuse error: C2338: template parameter is an integral of a size not supported on this platform

### ISSUE THREAD

**Issue by fanhenghui** [HerikLyma/CPPWebFramework#4]

**Comment by HerikLyma** [comment]
Hello fanhenghui, can you tell me in which file the error occurred and which compiler you are using?

NOTE: Make sure your compiler has C++ 11 enabled.

**Comment by HerikLyma** [comment]
Looking at your case, you're probably using an older version of Qt. Try using version 5.5 or higher.

**Comment by HerikLyma** [comment]
If you can not solve it, please let me know. I'll close this issue.

**Comment by sw0zwl** [comment]
Hello @HerikLyma , I met the same issue as same as above, and my Qt version is 5.11.3(win32), and the OS is win7.
