### ISSUE TITLE
Any SSL/https example please?

### ISSUE THREAD

**Issue by shujaatak** [HerikLyma/CPPWebFramework#7]
Is SSL supported? Any example with POST method and SSL please?

**Comment by HerikLyma** [comment]
Hello.

You can test the SSL in all CWF examples, just remove the ';' from these lines of the CPPWeb.ini

;sslKeyFile=/config/ssl/key.pem
;sslCertFile=/config/ssl/cert.pem
;sslPassPhrase=cppwebframework
;sslKeyAlgorithm=rsa
;sslEncodingFormat=pem
;sslKeyType=privatekey
;sslPeerVerifyMode=verifynone
;sslProtocol=tlsv1sslv3

and then, call https://localhost:8080
