### ISSUE TITLE
How can I use it as a simplest CMS?

### ISSUE THREAD

**Issue by shujaatak** [HerikLyma/CPPWebFramework#8]
Excuse me if this question feels too much newbie to you, what I want to do is to make CPPWebFramework to work as a simple CMS. Just having a functionality to post articles and surf them. Can you please give me some hints how to do this or upload an example which may demonstrate CMS functionality please?

**Comment by shujaatak** [comment]
As I have never programmed a CMS myself so I don't know how the articles will be fetched from Database. I don't know how a link will be resolved to some data inside database. I am also confused that when the user will click on a link in the web page for example **http://localhost:8080/this-is-article-heading** then how I will server find the article with heading "this is article heading"? Would I need to search articles in the database using heading? If this does not make sense to you then please excuse for this nonsense. Actually I am myself confused so I don't know how to phrase the question.

**Comment by kirtcathey** [comment]
This is not CMS software... as clearly stated on the web site.

**Comment by HerikLima** [comment]
Hello shujaatak, the CWF is not a CMS software.

Thank you.

**Comment by HerikLyma** [comment]
Hello shujaatak, the CWF is not a CMS software.

Thank you.
