### ISSUE TITLE
Server Not Handling Multiple Cookies Adequately

### ISSUE THREAD

**Issue by doumdi** [HerikLyma/CPPWebFramework#9]
I had to patch [HttpParser](https://github.com/HerikLyma/CPPWebFramework/blob/master/CPPWebFramework/cwf/httpparser.cpp#L138) To handle multiple cookies. [QNetworkCookie::parseCookies](http://code.qt.io/cgit/qt/qtbase.git/tree/src/network/access/qnetworkcookie.cpp?h=dev#n887) expects cookies separated by '\n' but the browsers send them separated by semicolons only. I replaced the line 
`const QByteArray &txt = temp[i];` by `QByteArray txt = temp[i].replace(";",";\n");` (adding a '\n' for every cookie) and it fixed the problem.

**Comment by doumdi** [comment]
This is such a small contribution, you can take credit for it. I am not sure though if it fits all use cases.

**Comment by HerikLyma** [comment]
Hello my friend.
This problem has been fixed.

Thanks for reporting it.
